// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/com.github/aeonlucid/pogoprotos/inventory/Item.proto

package com.github.aeonlucid.pogoprotos.inventory;

public final class Item {
  private Item() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemType}
   */
  public enum ItemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ITEM_TYPE_NONE = 0;</code>
     */
    ITEM_TYPE_NONE(0),
    /**
     * <code>ITEM_TYPE_POKEBALL = 1;</code>
     */
    ITEM_TYPE_POKEBALL(1),
    /**
     * <code>ITEM_TYPE_POTION = 2;</code>
     */
    ITEM_TYPE_POTION(2),
    /**
     * <code>ITEM_TYPE_REVIVE = 3;</code>
     */
    ITEM_TYPE_REVIVE(3),
    /**
     * <code>ITEM_TYPE_MAP = 4;</code>
     */
    ITEM_TYPE_MAP(4),
    /**
     * <code>ITEM_TYPE_BATTLE = 5;</code>
     */
    ITEM_TYPE_BATTLE(5),
    /**
     * <code>ITEM_TYPE_FOOD = 6;</code>
     */
    ITEM_TYPE_FOOD(6),
    /**
     * <code>ITEM_TYPE_CAMERA = 7;</code>
     */
    ITEM_TYPE_CAMERA(7),
    /**
     * <code>ITEM_TYPE_DISK = 8;</code>
     */
    ITEM_TYPE_DISK(8),
    /**
     * <code>ITEM_TYPE_INCUBATOR = 9;</code>
     */
    ITEM_TYPE_INCUBATOR(9),
    /**
     * <code>ITEM_TYPE_INCENSE = 10;</code>
     */
    ITEM_TYPE_INCENSE(10),
    /**
     * <code>ITEM_TYPE_XP_BOOST = 11;</code>
     */
    ITEM_TYPE_XP_BOOST(11),
    /**
     * <code>ITEM_TYPE_INVENTORY_UPGRADE = 12;</code>
     */
    ITEM_TYPE_INVENTORY_UPGRADE(12),
    /**
     * <code>ITEM_TYPE_EVOLUTION_REQUIREMENT = 13;</code>
     */
    ITEM_TYPE_EVOLUTION_REQUIREMENT(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ITEM_TYPE_NONE = 0;</code>
     */
    public static final int ITEM_TYPE_NONE_VALUE = 0;
    /**
     * <code>ITEM_TYPE_POKEBALL = 1;</code>
     */
    public static final int ITEM_TYPE_POKEBALL_VALUE = 1;
    /**
     * <code>ITEM_TYPE_POTION = 2;</code>
     */
    public static final int ITEM_TYPE_POTION_VALUE = 2;
    /**
     * <code>ITEM_TYPE_REVIVE = 3;</code>
     */
    public static final int ITEM_TYPE_REVIVE_VALUE = 3;
    /**
     * <code>ITEM_TYPE_MAP = 4;</code>
     */
    public static final int ITEM_TYPE_MAP_VALUE = 4;
    /**
     * <code>ITEM_TYPE_BATTLE = 5;</code>
     */
    public static final int ITEM_TYPE_BATTLE_VALUE = 5;
    /**
     * <code>ITEM_TYPE_FOOD = 6;</code>
     */
    public static final int ITEM_TYPE_FOOD_VALUE = 6;
    /**
     * <code>ITEM_TYPE_CAMERA = 7;</code>
     */
    public static final int ITEM_TYPE_CAMERA_VALUE = 7;
    /**
     * <code>ITEM_TYPE_DISK = 8;</code>
     */
    public static final int ITEM_TYPE_DISK_VALUE = 8;
    /**
     * <code>ITEM_TYPE_INCUBATOR = 9;</code>
     */
    public static final int ITEM_TYPE_INCUBATOR_VALUE = 9;
    /**
     * <code>ITEM_TYPE_INCENSE = 10;</code>
     */
    public static final int ITEM_TYPE_INCENSE_VALUE = 10;
    /**
     * <code>ITEM_TYPE_XP_BOOST = 11;</code>
     */
    public static final int ITEM_TYPE_XP_BOOST_VALUE = 11;
    /**
     * <code>ITEM_TYPE_INVENTORY_UPGRADE = 12;</code>
     */
    public static final int ITEM_TYPE_INVENTORY_UPGRADE_VALUE = 12;
    /**
     * <code>ITEM_TYPE_EVOLUTION_REQUIREMENT = 13;</code>
     */
    public static final int ITEM_TYPE_EVOLUTION_REQUIREMENT_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemType valueOf(int value) {
      return forNumber(value);
    }

    public static ItemType forNumber(int value) {
      switch (value) {
        case 0: return ITEM_TYPE_NONE;
        case 1: return ITEM_TYPE_POKEBALL;
        case 2: return ITEM_TYPE_POTION;
        case 3: return ITEM_TYPE_REVIVE;
        case 4: return ITEM_TYPE_MAP;
        case 5: return ITEM_TYPE_BATTLE;
        case 6: return ITEM_TYPE_FOOD;
        case 7: return ITEM_TYPE_CAMERA;
        case 8: return ITEM_TYPE_DISK;
        case 9: return ITEM_TYPE_INCUBATOR;
        case 10: return ITEM_TYPE_INCENSE;
        case 11: return ITEM_TYPE_XP_BOOST;
        case 12: return ITEM_TYPE_INVENTORY_UPGRADE;
        case 13: return ITEM_TYPE_EVOLUTION_REQUIREMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
            public ItemType findValueByNumber(int number) {
              return ItemType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.getDescriptor().getEnumTypes().get(0);
    }

    private static final ItemType[] VALUES = values();

    public static ItemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ItemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemType)
  }

  /**
   * Protobuf enum {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId}
   */
  public enum ItemId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ITEM_UNKNOWN = 0;</code>
     */
    ITEM_UNKNOWN(0),
    /**
     * <code>ITEM_POKE_BALL = 1;</code>
     */
    ITEM_POKE_BALL(1),
    /**
     * <code>ITEM_GREAT_BALL = 2;</code>
     */
    ITEM_GREAT_BALL(2),
    /**
     * <code>ITEM_ULTRA_BALL = 3;</code>
     */
    ITEM_ULTRA_BALL(3),
    /**
     * <code>ITEM_MASTER_BALL = 4;</code>
     */
    ITEM_MASTER_BALL(4),
    /**
     * <code>ITEM_POTION = 101;</code>
     */
    ITEM_POTION(101),
    /**
     * <code>ITEM_SUPER_POTION = 102;</code>
     */
    ITEM_SUPER_POTION(102),
    /**
     * <code>ITEM_HYPER_POTION = 103;</code>
     */
    ITEM_HYPER_POTION(103),
    /**
     * <code>ITEM_MAX_POTION = 104;</code>
     */
    ITEM_MAX_POTION(104),
    /**
     * <code>ITEM_REVIVE = 201;</code>
     */
    ITEM_REVIVE(201),
    /**
     * <code>ITEM_MAX_REVIVE = 202;</code>
     */
    ITEM_MAX_REVIVE(202),
    /**
     * <code>ITEM_LUCKY_EGG = 301;</code>
     */
    ITEM_LUCKY_EGG(301),
    /**
     * <code>ITEM_INCENSE_ORDINARY = 401;</code>
     */
    ITEM_INCENSE_ORDINARY(401),
    /**
     * <code>ITEM_INCENSE_SPICY = 402;</code>
     */
    ITEM_INCENSE_SPICY(402),
    /**
     * <code>ITEM_INCENSE_COOL = 403;</code>
     */
    ITEM_INCENSE_COOL(403),
    /**
     * <code>ITEM_INCENSE_FLORAL = 404;</code>
     */
    ITEM_INCENSE_FLORAL(404),
    /**
     * <code>ITEM_TROY_DISK = 501;</code>
     */
    ITEM_TROY_DISK(501),
    /**
     * <code>ITEM_X_ATTACK = 602;</code>
     */
    ITEM_X_ATTACK(602),
    /**
     * <code>ITEM_X_DEFENSE = 603;</code>
     */
    ITEM_X_DEFENSE(603),
    /**
     * <code>ITEM_X_MIRACLE = 604;</code>
     */
    ITEM_X_MIRACLE(604),
    /**
     * <code>ITEM_RAZZ_BERRY = 701;</code>
     */
    ITEM_RAZZ_BERRY(701),
    /**
     * <code>ITEM_BLUK_BERRY = 702;</code>
     */
    ITEM_BLUK_BERRY(702),
    /**
     * <code>ITEM_NANAB_BERRY = 703;</code>
     */
    ITEM_NANAB_BERRY(703),
    /**
     * <code>ITEM_WEPAR_BERRY = 704;</code>
     */
    ITEM_WEPAR_BERRY(704),
    /**
     * <code>ITEM_PINAP_BERRY = 705;</code>
     */
    ITEM_PINAP_BERRY(705),
    /**
     * <code>ITEM_SPECIAL_CAMERA = 801;</code>
     */
    ITEM_SPECIAL_CAMERA(801),
    /**
     * <code>ITEM_INCUBATOR_BASIC_UNLIMITED = 901;</code>
     */
    ITEM_INCUBATOR_BASIC_UNLIMITED(901),
    /**
     * <code>ITEM_INCUBATOR_BASIC = 902;</code>
     */
    ITEM_INCUBATOR_BASIC(902),
    /**
     * <code>ITEM_POKEMON_STORAGE_UPGRADE = 1001;</code>
     */
    ITEM_POKEMON_STORAGE_UPGRADE(1001),
    /**
     * <code>ITEM_ITEM_STORAGE_UPGRADE = 1002;</code>
     */
    ITEM_ITEM_STORAGE_UPGRADE(1002),
    /**
     * <code>ITEM_SUN_STONE = 1101;</code>
     */
    ITEM_SUN_STONE(1101),
    /**
     * <code>ITEM_KINGS_ROCK = 1102;</code>
     */
    ITEM_KINGS_ROCK(1102),
    /**
     * <code>ITEM_METAL_COAT = 1103;</code>
     */
    ITEM_METAL_COAT(1103),
    /**
     * <code>ITEM_DRAGON_SCALE = 1104;</code>
     */
    ITEM_DRAGON_SCALE(1104),
    /**
     * <code>ITEM_UP_GRADE = 1105;</code>
     */
    ITEM_UP_GRADE(1105),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ITEM_UNKNOWN = 0;</code>
     */
    public static final int ITEM_UNKNOWN_VALUE = 0;
    /**
     * <code>ITEM_POKE_BALL = 1;</code>
     */
    public static final int ITEM_POKE_BALL_VALUE = 1;
    /**
     * <code>ITEM_GREAT_BALL = 2;</code>
     */
    public static final int ITEM_GREAT_BALL_VALUE = 2;
    /**
     * <code>ITEM_ULTRA_BALL = 3;</code>
     */
    public static final int ITEM_ULTRA_BALL_VALUE = 3;
    /**
     * <code>ITEM_MASTER_BALL = 4;</code>
     */
    public static final int ITEM_MASTER_BALL_VALUE = 4;
    /**
     * <code>ITEM_POTION = 101;</code>
     */
    public static final int ITEM_POTION_VALUE = 101;
    /**
     * <code>ITEM_SUPER_POTION = 102;</code>
     */
    public static final int ITEM_SUPER_POTION_VALUE = 102;
    /**
     * <code>ITEM_HYPER_POTION = 103;</code>
     */
    public static final int ITEM_HYPER_POTION_VALUE = 103;
    /**
     * <code>ITEM_MAX_POTION = 104;</code>
     */
    public static final int ITEM_MAX_POTION_VALUE = 104;
    /**
     * <code>ITEM_REVIVE = 201;</code>
     */
    public static final int ITEM_REVIVE_VALUE = 201;
    /**
     * <code>ITEM_MAX_REVIVE = 202;</code>
     */
    public static final int ITEM_MAX_REVIVE_VALUE = 202;
    /**
     * <code>ITEM_LUCKY_EGG = 301;</code>
     */
    public static final int ITEM_LUCKY_EGG_VALUE = 301;
    /**
     * <code>ITEM_INCENSE_ORDINARY = 401;</code>
     */
    public static final int ITEM_INCENSE_ORDINARY_VALUE = 401;
    /**
     * <code>ITEM_INCENSE_SPICY = 402;</code>
     */
    public static final int ITEM_INCENSE_SPICY_VALUE = 402;
    /**
     * <code>ITEM_INCENSE_COOL = 403;</code>
     */
    public static final int ITEM_INCENSE_COOL_VALUE = 403;
    /**
     * <code>ITEM_INCENSE_FLORAL = 404;</code>
     */
    public static final int ITEM_INCENSE_FLORAL_VALUE = 404;
    /**
     * <code>ITEM_TROY_DISK = 501;</code>
     */
    public static final int ITEM_TROY_DISK_VALUE = 501;
    /**
     * <code>ITEM_X_ATTACK = 602;</code>
     */
    public static final int ITEM_X_ATTACK_VALUE = 602;
    /**
     * <code>ITEM_X_DEFENSE = 603;</code>
     */
    public static final int ITEM_X_DEFENSE_VALUE = 603;
    /**
     * <code>ITEM_X_MIRACLE = 604;</code>
     */
    public static final int ITEM_X_MIRACLE_VALUE = 604;
    /**
     * <code>ITEM_RAZZ_BERRY = 701;</code>
     */
    public static final int ITEM_RAZZ_BERRY_VALUE = 701;
    /**
     * <code>ITEM_BLUK_BERRY = 702;</code>
     */
    public static final int ITEM_BLUK_BERRY_VALUE = 702;
    /**
     * <code>ITEM_NANAB_BERRY = 703;</code>
     */
    public static final int ITEM_NANAB_BERRY_VALUE = 703;
    /**
     * <code>ITEM_WEPAR_BERRY = 704;</code>
     */
    public static final int ITEM_WEPAR_BERRY_VALUE = 704;
    /**
     * <code>ITEM_PINAP_BERRY = 705;</code>
     */
    public static final int ITEM_PINAP_BERRY_VALUE = 705;
    /**
     * <code>ITEM_SPECIAL_CAMERA = 801;</code>
     */
    public static final int ITEM_SPECIAL_CAMERA_VALUE = 801;
    /**
     * <code>ITEM_INCUBATOR_BASIC_UNLIMITED = 901;</code>
     */
    public static final int ITEM_INCUBATOR_BASIC_UNLIMITED_VALUE = 901;
    /**
     * <code>ITEM_INCUBATOR_BASIC = 902;</code>
     */
    public static final int ITEM_INCUBATOR_BASIC_VALUE = 902;
    /**
     * <code>ITEM_POKEMON_STORAGE_UPGRADE = 1001;</code>
     */
    public static final int ITEM_POKEMON_STORAGE_UPGRADE_VALUE = 1001;
    /**
     * <code>ITEM_ITEM_STORAGE_UPGRADE = 1002;</code>
     */
    public static final int ITEM_ITEM_STORAGE_UPGRADE_VALUE = 1002;
    /**
     * <code>ITEM_SUN_STONE = 1101;</code>
     */
    public static final int ITEM_SUN_STONE_VALUE = 1101;
    /**
     * <code>ITEM_KINGS_ROCK = 1102;</code>
     */
    public static final int ITEM_KINGS_ROCK_VALUE = 1102;
    /**
     * <code>ITEM_METAL_COAT = 1103;</code>
     */
    public static final int ITEM_METAL_COAT_VALUE = 1103;
    /**
     * <code>ITEM_DRAGON_SCALE = 1104;</code>
     */
    public static final int ITEM_DRAGON_SCALE_VALUE = 1104;
    /**
     * <code>ITEM_UP_GRADE = 1105;</code>
     */
    public static final int ITEM_UP_GRADE_VALUE = 1105;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemId valueOf(int value) {
      return forNumber(value);
    }

    public static ItemId forNumber(int value) {
      switch (value) {
        case 0: return ITEM_UNKNOWN;
        case 1: return ITEM_POKE_BALL;
        case 2: return ITEM_GREAT_BALL;
        case 3: return ITEM_ULTRA_BALL;
        case 4: return ITEM_MASTER_BALL;
        case 101: return ITEM_POTION;
        case 102: return ITEM_SUPER_POTION;
        case 103: return ITEM_HYPER_POTION;
        case 104: return ITEM_MAX_POTION;
        case 201: return ITEM_REVIVE;
        case 202: return ITEM_MAX_REVIVE;
        case 301: return ITEM_LUCKY_EGG;
        case 401: return ITEM_INCENSE_ORDINARY;
        case 402: return ITEM_INCENSE_SPICY;
        case 403: return ITEM_INCENSE_COOL;
        case 404: return ITEM_INCENSE_FLORAL;
        case 501: return ITEM_TROY_DISK;
        case 602: return ITEM_X_ATTACK;
        case 603: return ITEM_X_DEFENSE;
        case 604: return ITEM_X_MIRACLE;
        case 701: return ITEM_RAZZ_BERRY;
        case 702: return ITEM_BLUK_BERRY;
        case 703: return ITEM_NANAB_BERRY;
        case 704: return ITEM_WEPAR_BERRY;
        case 705: return ITEM_PINAP_BERRY;
        case 801: return ITEM_SPECIAL_CAMERA;
        case 901: return ITEM_INCUBATOR_BASIC_UNLIMITED;
        case 902: return ITEM_INCUBATOR_BASIC;
        case 1001: return ITEM_POKEMON_STORAGE_UPGRADE;
        case 1002: return ITEM_ITEM_STORAGE_UPGRADE;
        case 1101: return ITEM_SUN_STONE;
        case 1102: return ITEM_KINGS_ROCK;
        case 1103: return ITEM_METAL_COAT;
        case 1104: return ITEM_DRAGON_SCALE;
        case 1105: return ITEM_UP_GRADE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemId>() {
            public ItemId findValueByNumber(int number) {
              return ItemId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.getDescriptor().getEnumTypes().get(1);
    }

    private static final ItemId[] VALUES = values();

    public static ItemId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ItemId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId)
  }

  public interface ItemAwardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    int getItemIdValue();
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId();

    /**
     * <code>int32 item_count = 2;</code>
     */
    int getItemCount();

    /**
     * <code>int32 bonus_count = 3;</code>
     */
    int getBonusCount();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward}
   */
  public  static final class ItemAward extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
      ItemAwardOrBuilder {
    // Use ItemAward.newBuilder() to construct.
    private ItemAward(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemAward() {
      itemId_ = 0;
      itemCount_ = 0;
      bonusCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ItemAward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              itemId_ = rawValue;
              break;
            }
            case 16: {

              itemCount_ = input.readInt32();
              break;
            }
            case 24: {

              bonusCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.class, com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public int getItemIdValue() {
      return itemId_;
    }
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.valueOf(itemId_);
      return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
    }

    public static final int ITEM_COUNT_FIELD_NUMBER = 2;
    private int itemCount_;
    /**
     * <code>int32 item_count = 2;</code>
     */
    public int getItemCount() {
      return itemCount_;
    }

    public static final int BONUS_COUNT_FIELD_NUMBER = 3;
    private int bonusCount_;
    /**
     * <code>int32 bonus_count = 3;</code>
     */
    public int getBonusCount() {
      return bonusCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        output.writeEnum(1, itemId_);
      }
      if (itemCount_ != 0) {
        output.writeInt32(2, itemCount_);
      }
      if (bonusCount_ != 0) {
        output.writeInt32(3, bonusCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, itemId_);
      }
      if (itemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemCount_);
      }
      if (bonusCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bonusCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward other = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward) obj;

      boolean result = true;
      result = result && itemId_ == other.itemId_;
      result = result && (getItemCount()
          == other.getItemCount());
      result = result && (getBonusCount()
          == other.getBonusCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + itemId_;
      hash = (37 * hash) + ITEM_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getItemCount();
      hash = (37 * hash) + BONUS_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getBonusCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemAwardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.class, com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        itemCount_ = 0;

        bonusCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward build() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward buildPartial() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward result = new com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward(this);
        result.itemId_ = itemId_;
        result.itemCount_ = itemCount_;
        result.bonusCount_ = bonusCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward other) {
        if (other == com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward.getDefaultInstance()) return this;
        if (other.itemId_ != 0) {
          setItemIdValue(other.getItemIdValue());
        }
        if (other.getItemCount() != 0) {
          setItemCount(other.getItemCount());
        }
        if (other.getBonusCount() != 0) {
          setBonusCount(other.getBonusCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ = 0;
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public int getItemIdValue() {
        return itemId_;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemIdValue(int value) {
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.valueOf(itemId_);
        return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        itemId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }

      private int itemCount_ ;
      /**
       * <code>int32 item_count = 2;</code>
       */
      public int getItemCount() {
        return itemCount_;
      }
      /**
       * <code>int32 item_count = 2;</code>
       */
      public Builder setItemCount(int value) {
        
        itemCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 item_count = 2;</code>
       */
      public Builder clearItemCount() {
        
        itemCount_ = 0;
        onChanged();
        return this;
      }

      private int bonusCount_ ;
      /**
       * <code>int32 bonus_count = 3;</code>
       */
      public int getBonusCount() {
        return bonusCount_;
      }
      /**
       * <code>int32 bonus_count = 3;</code>
       */
      public Builder setBonusCount(int value) {
        
        bonusCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bonus_count = 3;</code>
       */
      public Builder clearBonusCount() {
        
        bonusCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemAward)
    private static final com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward();
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemAward>
        PARSER = new com.google.protobuf.AbstractParser<ItemAward>() {
      public ItemAward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ItemAward(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemAward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemAward> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemAward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    int getItemIdValue();
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId();

    /**
     * <code>int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>bool unseen = 3;</code>
     */
    boolean getUnseen();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData}
   */
  public  static final class ItemData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
      ItemDataOrBuilder {
    // Use ItemData.newBuilder() to construct.
    private ItemData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemData() {
      itemId_ = 0;
      count_ = 0;
      unseen_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ItemData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              itemId_ = rawValue;
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            case 24: {

              unseen_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.class, com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public int getItemIdValue() {
      return itemId_;
    }
    /**
     * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
     */
    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.valueOf(itemId_);
      return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int UNSEEN_FIELD_NUMBER = 3;
    private boolean unseen_;
    /**
     * <code>bool unseen = 3;</code>
     */
    public boolean getUnseen() {
      return unseen_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        output.writeEnum(1, itemId_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (unseen_ != false) {
        output.writeBool(3, unseen_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.ITEM_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, itemId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (unseen_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, unseen_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.inventory.Item.ItemData)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.inventory.Item.ItemData other = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemData) obj;

      boolean result = true;
      result = result && itemId_ == other.itemId_;
      result = result && (getCount()
          == other.getCount());
      result = result && (getUnseen()
          == other.getUnseen());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + itemId_;
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + UNSEEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnseen());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.inventory.Item.ItemData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.class, com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = 0;

        count_ = 0;

        unseen_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemData getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemData build() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemData buildPartial() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemData result = new com.github.aeonlucid.pogoprotos.inventory.Item.ItemData(this);
        result.itemId_ = itemId_;
        result.count_ = count_;
        result.unseen_ = unseen_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.inventory.Item.ItemData) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.inventory.Item.ItemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.inventory.Item.ItemData other) {
        if (other == com.github.aeonlucid.pogoprotos.inventory.Item.ItemData.getDefaultInstance()) return this;
        if (other.itemId_ != 0) {
          setItemIdValue(other.getItemIdValue());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getUnseen() != false) {
          setUnseen(other.getUnseen());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.inventory.Item.ItemData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int itemId_ = 0;
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public int getItemIdValue() {
        return itemId_;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemIdValue(int value) {
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public com.github.aeonlucid.pogoprotos.inventory.Item.ItemId getItemId() {
        com.github.aeonlucid.pogoprotos.inventory.Item.ItemId result = com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.valueOf(itemId_);
        return result == null ? com.github.aeonlucid.pogoprotos.inventory.Item.ItemId.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder setItemId(com.github.aeonlucid.pogoprotos.inventory.Item.ItemId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        itemId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.com.github.aeonlucid.pogoprotos.inventory.item.ItemId item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private boolean unseen_ ;
      /**
       * <code>bool unseen = 3;</code>
       */
      public boolean getUnseen() {
        return unseen_;
      }
      /**
       * <code>bool unseen = 3;</code>
       */
      public Builder setUnseen(boolean value) {
        
        unseen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool unseen = 3;</code>
       */
      public Builder clearUnseen() {
        
        unseen_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.inventory.item.ItemData)
    private static final com.github.aeonlucid.pogoprotos.inventory.Item.ItemData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.inventory.Item.ItemData();
    }

    public static com.github.aeonlucid.pogoprotos.inventory.Item.ItemData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemData>
        PARSER = new com.google.protobuf.AbstractParser<ItemData>() {
      public ItemData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ItemData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemData> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.inventory.Item.ItemData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4com/com.github/aeonlucid/pogoprotos/invent" +
      "ory/Item.proto\022.com.com.github.aeonlucid.pog" +
      "oprotos.inventory.item\"}\n\tItemAward\022G\n\007i" +
      "tem_id\030\001 \001(\01626.com.com.github.aeonlucid.pogo" +
      "protos.inventory.item.ItemId\022\022\n\nitem_cou" +
      "nt\030\002 \001(\005\022\023\n\013bonus_count\030\003 \001(\005\"r\n\010ItemDat" +
      "a\022G\n\007item_id\030\001 \001(\01626.com.com.github.aeonluci" +
      "d.pogoprotos.inventory.item.ItemId\022\r\n\005co" +
      "unt\030\002 \001(\005\022\016\n\006unseen\030\003 \001(\010*\327\002\n\010ItemType\022\022" +
      "\n\016ITEM_TYPE_NONE\020\000\022\026\n\022ITEM_TYPE_POKEBALL",
      "\020\001\022\024\n\020ITEM_TYPE_POTION\020\002\022\024\n\020ITEM_TYPE_RE" +
      "VIVE\020\003\022\021\n\rITEM_TYPE_MAP\020\004\022\024\n\020ITEM_TYPE_B" +
      "ATTLE\020\005\022\022\n\016ITEM_TYPE_FOOD\020\006\022\024\n\020ITEM_TYPE" +
      "_CAMERA\020\007\022\022\n\016ITEM_TYPE_DISK\020\010\022\027\n\023ITEM_TY" +
      "PE_INCUBATOR\020\t\022\025\n\021ITEM_TYPE_INCENSE\020\n\022\026\n" +
      "\022ITEM_TYPE_XP_BOOST\020\013\022\037\n\033ITEM_TYPE_INVEN" +
      "TORY_UPGRADE\020\014\022#\n\037ITEM_TYPE_EVOLUTION_RE" +
      "QUIREMENT\020\r*\264\006\n\006ItemId\022\020\n\014ITEM_UNKNOWN\020\000" +
      "\022\022\n\016ITEM_POKE_BALL\020\001\022\023\n\017ITEM_GREAT_BALL\020" +
      "\002\022\023\n\017ITEM_ULTRA_BALL\020\003\022\024\n\020ITEM_MASTER_BA",
      "LL\020\004\022\017\n\013ITEM_POTION\020e\022\025\n\021ITEM_SUPER_POTI" +
      "ON\020f\022\025\n\021ITEM_HYPER_POTION\020g\022\023\n\017ITEM_MAX_" +
      "POTION\020h\022\020\n\013ITEM_REVIVE\020\311\001\022\024\n\017ITEM_MAX_R" +
      "EVIVE\020\312\001\022\023\n\016ITEM_LUCKY_EGG\020\255\002\022\032\n\025ITEM_IN" +
      "CENSE_ORDINARY\020\221\003\022\027\n\022ITEM_INCENSE_SPICY\020" +
      "\222\003\022\026\n\021ITEM_INCENSE_COOL\020\223\003\022\030\n\023ITEM_INCEN" +
      "SE_FLORAL\020\224\003\022\023\n\016ITEM_TROY_DISK\020\365\003\022\022\n\rITE" +
      "M_X_ATTACK\020\332\004\022\023\n\016ITEM_X_DEFENSE\020\333\004\022\023\n\016IT" +
      "EM_X_MIRACLE\020\334\004\022\024\n\017ITEM_RAZZ_BERRY\020\275\005\022\024\n" +
      "\017ITEM_BLUK_BERRY\020\276\005\022\025\n\020ITEM_NANAB_BERRY\020",
      "\277\005\022\025\n\020ITEM_WEPAR_BERRY\020\300\005\022\025\n\020ITEM_PINAP_" +
      "BERRY\020\301\005\022\030\n\023ITEM_SPECIAL_CAMERA\020\241\006\022#\n\036IT" +
      "EM_INCUBATOR_BASIC_UNLIMITED\020\205\007\022\031\n\024ITEM_" +
      "INCUBATOR_BASIC\020\206\007\022!\n\034ITEM_POKEMON_STORA" +
      "GE_UPGRADE\020\351\007\022\036\n\031ITEM_ITEM_STORAGE_UPGRA" +
      "DE\020\352\007\022\023\n\016ITEM_SUN_STONE\020\315\010\022\024\n\017ITEM_KINGS" +
      "_ROCK\020\316\010\022\024\n\017ITEM_METAL_COAT\020\317\010\022\026\n\021ITEM_D" +
      "RAGON_SCALE\020\320\010\022\022\n\rITEM_UP_GRADE\020\321\010B1\n)co" +
      "m.com.github.aeonlucid.pogoprotos.inventoryB" +
      "\004Itemb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemAward_descriptor,
        new java.lang.String[] { "ItemId", "ItemCount", "BonusCount", });
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_inventory_item_ItemData_descriptor,
        new java.lang.String[] { "ItemId", "Count", "Unseen", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
