// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/com.github/aeonlucid/pogoprotos/networking/platform/Requests.proto

package com.github.aeonlucid.pogoprotos.networking.platform;

public final class Requests {
  private Requests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendEncryptedSignatureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes encrypted_signature = 1;</code>
     */
    com.google.protobuf.ByteString getEncryptedSignature();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest}
   */
  public  static final class SendEncryptedSignatureRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
      SendEncryptedSignatureRequestOrBuilder {
    // Use SendEncryptedSignatureRequest.newBuilder() to construct.
    private SendEncryptedSignatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendEncryptedSignatureRequest() {
      encryptedSignature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SendEncryptedSignatureRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              encryptedSignature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.Builder.class);
    }

    public static final int ENCRYPTED_SIGNATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encryptedSignature_;
    /**
     * <code>bytes encrypted_signature = 1;</code>
     */
    public com.google.protobuf.ByteString getEncryptedSignature() {
      return encryptedSignature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encryptedSignature_.isEmpty()) {
        output.writeBytes(1, encryptedSignature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encryptedSignature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encryptedSignature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest) obj;

      boolean result = true;
      result = result && getEncryptedSignature()
          .equals(other.getEncryptedSignature());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCRYPTED_SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        encryptedSignature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest build() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest buildPartial() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest result = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest(this);
        result.encryptedSignature_ = encryptedSignature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest other) {
        if (other == com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest.getDefaultInstance()) return this;
        if (other.getEncryptedSignature() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptedSignature(other.getEncryptedSignature());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encryptedSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encrypted_signature = 1;</code>
       */
      public com.google.protobuf.ByteString getEncryptedSignature() {
        return encryptedSignature_;
      }
      /**
       * <code>bytes encrypted_signature = 1;</code>
       */
      public Builder setEncryptedSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encryptedSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encrypted_signature = 1;</code>
       */
      public Builder clearEncryptedSignature() {
        
        encryptedSignature_ = getDefaultInstance().getEncryptedSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.SendEncryptedSignatureRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendEncryptedSignatureRequest>
        PARSER = new com.google.protobuf.AbstractParser<SendEncryptedSignatureRequest>() {
      public SendEncryptedSignatureRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SendEncryptedSignatureRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendEncryptedSignatureRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendEncryptedSignatureRequest> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.networking.platform.Requests.SendEncryptedSignatureRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuyItemAndroidRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>string buy_item_intent = 1;</code>
     */
    java.lang.String getBuyItemIntent();
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>string buy_item_intent = 1;</code>
     */
    com.google.protobuf.ByteString
        getBuyItemIntentBytes();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest}
   */
  public  static final class BuyItemAndroidRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
      BuyItemAndroidRequestOrBuilder {
    // Use BuyItemAndroidRequest.newBuilder() to construct.
    private BuyItemAndroidRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuyItemAndroidRequest() {
      buyItemIntent_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BuyItemAndroidRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buyItemIntent_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.Builder.class);
    }

    public static final int BUY_ITEM_INTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object buyItemIntent_;
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>string buy_item_intent = 1;</code>
     */
    public java.lang.String getBuyItemIntent() {
      java.lang.Object ref = buyItemIntent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyItemIntent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * see https://developer.android.com/google/play/billing/billing_reference.html table 4
     * </pre>
     *
     * <code>string buy_item_intent = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBuyItemIntentBytes() {
      java.lang.Object ref = buyItemIntent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyItemIntent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBuyItemIntentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buyItemIntent_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBuyItemIntentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buyItemIntent_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest) obj;

      boolean result = true;
      result = result && getBuyItemIntent()
          .equals(other.getBuyItemIntent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUY_ITEM_INTENT_FIELD_NUMBER;
      hash = (53 * hash) + getBuyItemIntent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        buyItemIntent_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest build() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest buildPartial() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest result = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest(this);
        result.buyItemIntent_ = buyItemIntent_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest other) {
        if (other == com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest.getDefaultInstance()) return this;
        if (!other.getBuyItemIntent().isEmpty()) {
          buyItemIntent_ = other.buyItemIntent_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buyItemIntent_ = "";
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>string buy_item_intent = 1;</code>
       */
      public java.lang.String getBuyItemIntent() {
        java.lang.Object ref = buyItemIntent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buyItemIntent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>string buy_item_intent = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBuyItemIntentBytes() {
        java.lang.Object ref = buyItemIntent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyItemIntent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>string buy_item_intent = 1;</code>
       */
      public Builder setBuyItemIntent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buyItemIntent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>string buy_item_intent = 1;</code>
       */
      public Builder clearBuyItemIntent() {
        
        buyItemIntent_ = getDefaultInstance().getBuyItemIntent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * see https://developer.android.com/google/play/billing/billing_reference.html table 4
       * </pre>
       *
       * <code>string buy_item_intent = 1;</code>
       */
      public Builder setBuyItemIntentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buyItemIntent_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemAndroidRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuyItemAndroidRequest>
        PARSER = new com.google.protobuf.AbstractParser<BuyItemAndroidRequest>() {
      public BuyItemAndroidRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BuyItemAndroidRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuyItemAndroidRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuyItemAndroidRequest> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemAndroidRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnknownPtr8RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request}
   */
  public  static final class UnknownPtr8Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request)
      UnknownPtr8RequestOrBuilder {
    // Use UnknownPtr8Request.newBuilder() to construct.
    private UnknownPtr8Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnknownPtr8Request() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UnknownPtr8Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request build() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request buildPartial() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request result = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request other) {
        if (other == com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.UnknownPtr8Request)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnknownPtr8Request>
        PARSER = new com.google.protobuf.AbstractParser<UnknownPtr8Request>() {
      public UnknownPtr8Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UnknownPtr8Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnknownPtr8Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnknownPtr8Request> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.networking.platform.Requests.UnknownPtr8Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuyItemPokeCoinsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string item_id = 1;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>string item_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest}
   */
  public  static final class BuyItemPokeCoinsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
      BuyItemPokeCoinsRequestOrBuilder {
    // Use BuyItemPokeCoinsRequest.newBuilder() to construct.
    private BuyItemPokeCoinsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuyItemPokeCoinsRequest() {
      itemId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BuyItemPokeCoinsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              itemId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.Builder.class);
    }

    public static final int ITEM_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object itemId_;
    /**
     * <code>string item_id = 1;</code>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemId_ = s;
        return s;
      }
    }
    /**
     * <code>string item_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getItemIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, itemId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getItemIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, itemId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest other = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest) obj;

      boolean result = true;
      result = result && getItemId()
          .equals(other.getItemId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getItemId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.class, com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        itemId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest build() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest buildPartial() {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest result = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest(this);
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest other) {
        if (other == com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest.getDefaultInstance()) return this;
        if (!other.getItemId().isEmpty()) {
          itemId_ = other.itemId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object itemId_ = "";
      /**
       * <code>string item_id = 1;</code>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder clearItemId() {
        
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>string item_id = 1;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.networking.platform.requests.BuyItemPokeCoinsRequest)
    private static final com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest();
    }

    public static com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuyItemPokeCoinsRequest>
        PARSER = new com.google.protobuf.AbstractParser<BuyItemPokeCoinsRequest>() {
      public BuyItemPokeCoinsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BuyItemPokeCoinsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuyItemPokeCoinsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuyItemPokeCoinsRequest> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.networking.platform.Requests.BuyItemPokeCoinsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBcom/com.github/aeonlucid/pogoprotos/networ" +
      "king/platform/Requests.proto\022<com.com.github" +
      ".aeonlucid.pogoprotos.networking.platfor" +
      "m.requests\"<\n\035SendEncryptedSignatureRequ" +
      "est\022\033\n\023encrypted_signature\030\001 \001(\014\"0\n\025BuyI" +
      "temAndroidRequest\022\027\n\017buy_item_intent\030\001 \001" +
      "(\t\"%\n\022UnknownPtr8Request\022\017\n\007message\030\001 \001(" +
      "\t\"*\n\027BuyItemPokeCoinsRequest\022\017\n\007item_id\030" +
      "\001 \001(\tB?\n3com.com.github.aeonlucid.pogoprotos" +
      ".networking.platformB\010Requestsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_SendEncryptedSignatureRequest_descriptor,
        new java.lang.String[] { "EncryptedSignature", });
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemAndroidRequest_descriptor,
        new java.lang.String[] { "BuyItemIntent", });
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_UnknownPtr8Request_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_networking_platform_requests_BuyItemPokeCoinsRequest_descriptor,
        new java.lang.String[] { "ItemId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
