/*
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.pokegoapi.api.pokemon;

import POGOProtos.Enums.PokemonIdOuterClass;
import lombok.Getter;

public class PokemonMeta {
	@Getter
	private int baseStam;
	@Getter
	private double baseCaptureRate;
	@Getter
	private int candiesToEvolve;
	@Getter
	private double baseFleeRate;
	@Getter
	private PokemonIdOuterClass.PokemonId parent;

	/**
	 * Instantiates a meta pokemon data.
	 *
	 * @param baseStam
	 *            autogenerated
	 * @param baseCaptureRate
	 *            autogenerated
	 * @param candiesToEvolve
	 *            autogenerated
	 * @param baseFleeRate
	 *            autogenerated
	 * @param pokedexHeight
	 *            autogenerated
	 * @param parent
	 *            autogenerated
	 */
	public PokemonMeta(	int baseStam,
						double baseCaptureRate,
						int candiesToEvolve,
						double baseFleeRate,
						double pokedexHeight,
						PokemonIdOuterClass.PokemonId parent) {
		// did not mean to include pokedex height in output
		this.baseStam = baseStam;
		this.baseCaptureRate = baseCaptureRate;
		this.candiesToEvolve = candiesToEvolve;
		this.baseFleeRate = baseFleeRate;
		this.parent = parent;
	}
}
