// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/com.github/aeonlucid/pogoprotos/data/Avatar.proto

package com.github.aeonlucid.pogoprotos.data;

public final class Avatar {
  private Avatar() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AvatarItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string avatar_template_id = 1;</code>
     */
    java.lang.String getAvatarTemplateId();
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getAvatarTemplateIdBytes();

    /**
     * <code>int64 new_timestamp_ms = 2;</code>
     */
    long getNewTimestampMs();

    /**
     * <code>bool viewed = 3;</code>
     */
    boolean getViewed();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem}
   */
  public  static final class AvatarItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem)
      AvatarItemOrBuilder {
    // Use AvatarItem.newBuilder() to construct.
    private AvatarItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvatarItem() {
      avatarTemplateId_ = "";
      newTimestampMs_ = 0L;
      viewed_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AvatarItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              avatarTemplateId_ = s;
              break;
            }
            case 16: {

              newTimestampMs_ = input.readInt64();
              break;
            }
            case 24: {

              viewed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.class, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.Builder.class);
    }

    public static final int AVATAR_TEMPLATE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object avatarTemplateId_;
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public java.lang.String getAvatarTemplateId() {
      java.lang.Object ref = avatarTemplateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarTemplateId_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarTemplateIdBytes() {
      java.lang.Object ref = avatarTemplateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarTemplateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEW_TIMESTAMP_MS_FIELD_NUMBER = 2;
    private long newTimestampMs_;
    /**
     * <code>int64 new_timestamp_ms = 2;</code>
     */
    public long getNewTimestampMs() {
      return newTimestampMs_;
    }

    public static final int VIEWED_FIELD_NUMBER = 3;
    private boolean viewed_;
    /**
     * <code>bool viewed = 3;</code>
     */
    public boolean getViewed() {
      return viewed_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAvatarTemplateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, avatarTemplateId_);
      }
      if (newTimestampMs_ != 0L) {
        output.writeInt64(2, newTimestampMs_);
      }
      if (viewed_ != false) {
        output.writeBool(3, viewed_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAvatarTemplateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, avatarTemplateId_);
      }
      if (newTimestampMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, newTimestampMs_);
      }
      if (viewed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, viewed_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem other = (com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem) obj;

      boolean result = true;
      result = result && getAvatarTemplateId()
          .equals(other.getAvatarTemplateId());
      result = result && (getNewTimestampMs()
          == other.getNewTimestampMs());
      result = result && (getViewed()
          == other.getViewed());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AVATAR_TEMPLATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarTemplateId().hashCode();
      hash = (37 * hash) + NEW_TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNewTimestampMs());
      hash = (37 * hash) + VIEWED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getViewed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem)
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.class, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        avatarTemplateId_ = "";

        newTimestampMs_ = 0L;

        viewed_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem build() {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem buildPartial() {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem result = new com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem(this);
        result.avatarTemplateId_ = avatarTemplateId_;
        result.newTimestampMs_ = newTimestampMs_;
        result.viewed_ = viewed_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem other) {
        if (other == com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem.getDefaultInstance()) return this;
        if (!other.getAvatarTemplateId().isEmpty()) {
          avatarTemplateId_ = other.avatarTemplateId_;
          onChanged();
        }
        if (other.getNewTimestampMs() != 0L) {
          setNewTimestampMs(other.getNewTimestampMs());
        }
        if (other.getViewed() != false) {
          setViewed(other.getViewed());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object avatarTemplateId_ = "";
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public java.lang.String getAvatarTemplateId() {
        java.lang.Object ref = avatarTemplateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatarTemplateId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarTemplateIdBytes() {
        java.lang.Object ref = avatarTemplateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatarTemplateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder setAvatarTemplateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarTemplateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder clearAvatarTemplateId() {
        
        avatarTemplateId_ = getDefaultInstance().getAvatarTemplateId();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder setAvatarTemplateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarTemplateId_ = value;
        onChanged();
        return this;
      }

      private long newTimestampMs_ ;
      /**
       * <code>int64 new_timestamp_ms = 2;</code>
       */
      public long getNewTimestampMs() {
        return newTimestampMs_;
      }
      /**
       * <code>int64 new_timestamp_ms = 2;</code>
       */
      public Builder setNewTimestampMs(long value) {
        
        newTimestampMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 new_timestamp_ms = 2;</code>
       */
      public Builder clearNewTimestampMs() {
        
        newTimestampMs_ = 0L;
        onChanged();
        return this;
      }

      private boolean viewed_ ;
      /**
       * <code>bool viewed = 3;</code>
       */
      public boolean getViewed() {
        return viewed_;
      }
      /**
       * <code>bool viewed = 3;</code>
       */
      public Builder setViewed(boolean value) {
        
        viewed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool viewed = 3;</code>
       */
      public Builder clearViewed() {
        
        viewed_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarItem)
    private static final com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem();
    }

    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvatarItem>
        PARSER = new com.google.protobuf.AbstractParser<AvatarItem>() {
      public AvatarItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AvatarItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvatarItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvatarItem> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AvatarCustomizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string avatar_template_id = 1;</code>
     */
    java.lang.String getAvatarTemplateId();
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getAvatarTemplateIdBytes();

    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    java.util.List<com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label> getLabelsList();
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    int getLabelsCount();
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label getLabels(int index);
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    java.util.List<java.lang.Integer>
    getLabelsValueList();
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    int getLabelsValue(int index);
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization}
   */
  public  static final class AvatarCustomization extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization)
      AvatarCustomizationOrBuilder {
    // Use AvatarCustomization.newBuilder() to construct.
    private AvatarCustomization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvatarCustomization() {
      avatarTemplateId_ = "";
      labels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AvatarCustomization(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              avatarTemplateId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                labels_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              labels_.add(rawValue);
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  labels_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                labels_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.class, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Builder.class);
    }

    /**
     * Protobuf enum {@code com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label}
     */
    public enum Label
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNSET_LABEL = 0;</code>
       */
      UNSET_LABEL(0),
      /**
       * <code>DEFAULT = 1;</code>
       */
      DEFAULT(1),
      /**
       * <code>OWNED = 2;</code>
       */
      OWNED(2),
      /**
       * <code>FEATURED = 3;</code>
       */
      FEATURED(3),
      /**
       * <code>NEW = 4;</code>
       */
      NEW(4),
      /**
       * <code>SALE = 5;</code>
       */
      SALE(5),
      /**
       * <code>PURCHASABLE = 6;</code>
       */
      PURCHASABLE(6),
      /**
       * <code>UNLOCKABLE = 7;</code>
       */
      UNLOCKABLE(7),
      /**
       * <code>VIEWED = 8;</code>
       */
      VIEWED(8),
      /**
       * <code>LOCKED_PURCHASABLE = 9;</code>
       */
      LOCKED_PURCHASABLE(9),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNSET_LABEL = 0;</code>
       */
      public static final int UNSET_LABEL_VALUE = 0;
      /**
       * <code>DEFAULT = 1;</code>
       */
      public static final int DEFAULT_VALUE = 1;
      /**
       * <code>OWNED = 2;</code>
       */
      public static final int OWNED_VALUE = 2;
      /**
       * <code>FEATURED = 3;</code>
       */
      public static final int FEATURED_VALUE = 3;
      /**
       * <code>NEW = 4;</code>
       */
      public static final int NEW_VALUE = 4;
      /**
       * <code>SALE = 5;</code>
       */
      public static final int SALE_VALUE = 5;
      /**
       * <code>PURCHASABLE = 6;</code>
       */
      public static final int PURCHASABLE_VALUE = 6;
      /**
       * <code>UNLOCKABLE = 7;</code>
       */
      public static final int UNLOCKABLE_VALUE = 7;
      /**
       * <code>VIEWED = 8;</code>
       */
      public static final int VIEWED_VALUE = 8;
      /**
       * <code>LOCKED_PURCHASABLE = 9;</code>
       */
      public static final int LOCKED_PURCHASABLE_VALUE = 9;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Label valueOf(int value) {
        return forNumber(value);
      }

      public static Label forNumber(int value) {
        switch (value) {
          case 0: return UNSET_LABEL;
          case 1: return DEFAULT;
          case 2: return OWNED;
          case 3: return FEATURED;
          case 4: return NEW;
          case 5: return SALE;
          case 6: return PURCHASABLE;
          case 7: return UNLOCKABLE;
          case 8: return VIEWED;
          case 9: return LOCKED_PURCHASABLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Label>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Label> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Label>() {
              public Label findValueByNumber(int number) {
                return Label.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.getDescriptor().getEnumTypes().get(0);
      }

      private static final Label[] VALUES = values();

      public static Label valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Label(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label)
    }

    private int bitField0_;
    public static final int AVATAR_TEMPLATE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object avatarTemplateId_;
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public java.lang.String getAvatarTemplateId() {
      java.lang.Object ref = avatarTemplateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarTemplateId_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar_template_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarTemplateIdBytes() {
      java.lang.Object ref = avatarTemplateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarTemplateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABELS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> labels_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label> labels_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label>() {
              public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label convert(java.lang.Integer from) {
                com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label result = com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label.valueOf(from);
                return result == null ? com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public java.util.List<com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label> getLabelsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label>(labels_, labels_converter_);
    }
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label getLabels(int index) {
      return labels_converter_.convert(labels_.get(index));
    }
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public java.util.List<java.lang.Integer>
    getLabelsValueList() {
      return labels_;
    }
    /**
     * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
     */
    public int getLabelsValue(int index) {
      return labels_.get(index);
    }
    private int labelsMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getAvatarTemplateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, avatarTemplateId_);
      }
      if (getLabelsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(labelsMemoizedSerializedSize);
      }
      for (int i = 0; i < labels_.size(); i++) {
        output.writeEnumNoTag(labels_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAvatarTemplateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, avatarTemplateId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < labels_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(labels_.get(i));
        }
        size += dataSize;
        if (!getLabelsList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }labelsMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization other = (com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization) obj;

      boolean result = true;
      result = result && getAvatarTemplateId()
          .equals(other.getAvatarTemplateId());
      result = result && labels_.equals(other.labels_);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AVATAR_TEMPLATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarTemplateId().hashCode();
      if (getLabelsCount() > 0) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + labels_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization)
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomizationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.class, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        avatarTemplateId_ = "";

        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization build() {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization buildPartial() {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization result = new com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.avatarTemplateId_ = avatarTemplateId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.labels_ = labels_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization other) {
        if (other == com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.getDefaultInstance()) return this;
        if (!other.getAvatarTemplateId().isEmpty()) {
          avatarTemplateId_ = other.avatarTemplateId_;
          onChanged();
        }
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object avatarTemplateId_ = "";
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public java.lang.String getAvatarTemplateId() {
        java.lang.Object ref = avatarTemplateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatarTemplateId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarTemplateIdBytes() {
        java.lang.Object ref = avatarTemplateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatarTemplateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder setAvatarTemplateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarTemplateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder clearAvatarTemplateId() {
        
        avatarTemplateId_ = getDefaultInstance().getAvatarTemplateId();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar_template_id = 1;</code>
       */
      public Builder setAvatarTemplateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarTemplateId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> labels_ =
        java.util.Collections.emptyList();
      private void ensureLabelsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          labels_ = new java.util.ArrayList<java.lang.Integer>(labels_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public java.util.List<com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label> getLabelsList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label>(labels_, labels_converter_);
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public int getLabelsCount() {
        return labels_.size();
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label getLabels(int index) {
        return labels_converter_.convert(labels_.get(index));
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder setLabels(
          int index, com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder addLabels(com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder addAllLabels(
          java.lang.Iterable<? extends com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label> values) {
        ensureLabelsIsMutable();
        for (com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization.Label value : values) {
          labels_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder clearLabels() {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public java.util.List<java.lang.Integer>
      getLabelsValueList() {
        return java.util.Collections.unmodifiableList(labels_);
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public int getLabelsValue(int index) {
        return labels_.get(index);
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder setLabelsValue(
          int index, int value) {
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder addLabelsValue(int value) {
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization.Label labels = 2;</code>
       */
      public Builder addAllLabelsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureLabelsIsMutable();
        for (int value : values) {
          labels_.add(value);
        }
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.data.avatar.AvatarCustomization)
    private static final com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization();
    }

    public static com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvatarCustomization>
        PARSER = new com.google.protobuf.AbstractParser<AvatarCustomization>() {
      public AvatarCustomization parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AvatarCustomization(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvatarCustomization> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvatarCustomization> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.data.Avatar.AvatarCustomization getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1com/com.github/aeonlucid/pogoprotos/data/A" +
      "vatar.proto\022+com.com.github.aeonlucid.pogopr" +
      "otos.data.avatar\"R\n\nAvatarItem\022\032\n\022avatar" +
      "_template_id\030\001 \001(\t\022\030\n\020new_timestamp_ms\030\002" +
      " \001(\003\022\016\n\006viewed\030\003 \001(\010\"\242\002\n\023AvatarCustomiza" +
      "tion\022\032\n\022avatar_template_id\030\001 \001(\t\022V\n\006labe" +
      "ls\030\002 \003(\0162F.com.com.github.aeonlucid.pogoprot" +
      "os.data.avatar.AvatarCustomization.Label" +
      "\"\226\001\n\005Label\022\017\n\013UNSET_LABEL\020\000\022\013\n\007DEFAULT\020\001" +
      "\022\t\n\005OWNED\020\002\022\014\n\010FEATURED\020\003\022\007\n\003NEW\020\004\022\010\n\004SA",
      "LE\020\005\022\017\n\013PURCHASABLE\020\006\022\016\n\nUNLOCKABLE\020\007\022\n\n" +
      "\006VIEWED\020\010\022\026\n\022LOCKED_PURCHASABLE\020\tB.\n$com" +
      ".com.github.aeonlucid.pogoprotos.dataB\006Avata" +
      "rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarItem_descriptor,
        new java.lang.String[] { "AvatarTemplateId", "NewTimestampMs", "Viewed", });
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_data_avatar_AvatarCustomization_descriptor,
        new java.lang.String[] { "AvatarTemplateId", "Labels", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
