// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/com.github/aeonlucid/pogoprotos/settings/master/Quest.proto

package com.github.aeonlucid.pogoprotos.settings.master;

public final class Quest {
  private Quest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DailyQuestSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 buckets_per_day = 1;</code>
     */
    int getBucketsPerDay();

    /**
     * <code>int32 streak_length = 2;</code>
     */
    int getStreakLength();

    /**
     * <code>float bonus_multiplier = 3;</code>
     */
    float getBonusMultiplier();

    /**
     * <code>float streak_bonus_multiplier = 4;</code>
     */
    float getStreakBonusMultiplier();
  }
  /**
   * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings}
   */
  public  static final class DailyQuestSettings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings)
      DailyQuestSettingsOrBuilder {
    // Use DailyQuestSettings.newBuilder() to construct.
    private DailyQuestSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DailyQuestSettings() {
      bucketsPerDay_ = 0;
      streakLength_ = 0;
      bonusMultiplier_ = 0F;
      streakBonusMultiplier_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DailyQuestSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bucketsPerDay_ = input.readInt32();
              break;
            }
            case 16: {

              streakLength_ = input.readInt32();
              break;
            }
            case 29: {

              bonusMultiplier_ = input.readFloat();
              break;
            }
            case 37: {

              streakBonusMultiplier_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aeonlucid.pogoprotos.settings.master.Quest.internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aeonlucid.pogoprotos.settings.master.Quest.internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.class, com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.Builder.class);
    }

    public static final int BUCKETS_PER_DAY_FIELD_NUMBER = 1;
    private int bucketsPerDay_;
    /**
     * <code>int32 buckets_per_day = 1;</code>
     */
    public int getBucketsPerDay() {
      return bucketsPerDay_;
    }

    public static final int STREAK_LENGTH_FIELD_NUMBER = 2;
    private int streakLength_;
    /**
     * <code>int32 streak_length = 2;</code>
     */
    public int getStreakLength() {
      return streakLength_;
    }

    public static final int BONUS_MULTIPLIER_FIELD_NUMBER = 3;
    private float bonusMultiplier_;
    /**
     * <code>float bonus_multiplier = 3;</code>
     */
    public float getBonusMultiplier() {
      return bonusMultiplier_;
    }

    public static final int STREAK_BONUS_MULTIPLIER_FIELD_NUMBER = 4;
    private float streakBonusMultiplier_;
    /**
     * <code>float streak_bonus_multiplier = 4;</code>
     */
    public float getStreakBonusMultiplier() {
      return streakBonusMultiplier_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bucketsPerDay_ != 0) {
        output.writeInt32(1, bucketsPerDay_);
      }
      if (streakLength_ != 0) {
        output.writeInt32(2, streakLength_);
      }
      if (bonusMultiplier_ != 0F) {
        output.writeFloat(3, bonusMultiplier_);
      }
      if (streakBonusMultiplier_ != 0F) {
        output.writeFloat(4, streakBonusMultiplier_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bucketsPerDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bucketsPerDay_);
      }
      if (streakLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, streakLength_);
      }
      if (bonusMultiplier_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, bonusMultiplier_);
      }
      if (streakBonusMultiplier_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, streakBonusMultiplier_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings)) {
        return super.equals(obj);
      }
      com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings other = (com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings) obj;

      boolean result = true;
      result = result && (getBucketsPerDay()
          == other.getBucketsPerDay());
      result = result && (getStreakLength()
          == other.getStreakLength());
      result = result && (
          java.lang.Float.floatToIntBits(getBonusMultiplier())
          == java.lang.Float.floatToIntBits(
              other.getBonusMultiplier()));
      result = result && (
          java.lang.Float.floatToIntBits(getStreakBonusMultiplier())
          == java.lang.Float.floatToIntBits(
              other.getStreakBonusMultiplier()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUCKETS_PER_DAY_FIELD_NUMBER;
      hash = (53 * hash) + getBucketsPerDay();
      hash = (37 * hash) + STREAK_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getStreakLength();
      hash = (37 * hash) + BONUS_MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBonusMultiplier());
      hash = (37 * hash) + STREAK_BONUS_MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStreakBonusMultiplier());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings)
        com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aeonlucid.pogoprotos.settings.master.Quest.internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aeonlucid.pogoprotos.settings.master.Quest.internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.class, com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.Builder.class);
      }

      // Construct using com.com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bucketsPerDay_ = 0;

        streakLength_ = 0;

        bonusMultiplier_ = 0F;

        streakBonusMultiplier_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Quest.internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings getDefaultInstanceForType() {
        return com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.getDefaultInstance();
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings build() {
        com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings buildPartial() {
        com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings result = new com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings(this);
        result.bucketsPerDay_ = bucketsPerDay_;
        result.streakLength_ = streakLength_;
        result.bonusMultiplier_ = bonusMultiplier_;
        result.streakBonusMultiplier_ = streakBonusMultiplier_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings) {
          return mergeFrom((com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings other) {
        if (other == com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings.getDefaultInstance()) return this;
        if (other.getBucketsPerDay() != 0) {
          setBucketsPerDay(other.getBucketsPerDay());
        }
        if (other.getStreakLength() != 0) {
          setStreakLength(other.getStreakLength());
        }
        if (other.getBonusMultiplier() != 0F) {
          setBonusMultiplier(other.getBonusMultiplier());
        }
        if (other.getStreakBonusMultiplier() != 0F) {
          setStreakBonusMultiplier(other.getStreakBonusMultiplier());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bucketsPerDay_ ;
      /**
       * <code>int32 buckets_per_day = 1;</code>
       */
      public int getBucketsPerDay() {
        return bucketsPerDay_;
      }
      /**
       * <code>int32 buckets_per_day = 1;</code>
       */
      public Builder setBucketsPerDay(int value) {
        
        bucketsPerDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buckets_per_day = 1;</code>
       */
      public Builder clearBucketsPerDay() {
        
        bucketsPerDay_ = 0;
        onChanged();
        return this;
      }

      private int streakLength_ ;
      /**
       * <code>int32 streak_length = 2;</code>
       */
      public int getStreakLength() {
        return streakLength_;
      }
      /**
       * <code>int32 streak_length = 2;</code>
       */
      public Builder setStreakLength(int value) {
        
        streakLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 streak_length = 2;</code>
       */
      public Builder clearStreakLength() {
        
        streakLength_ = 0;
        onChanged();
        return this;
      }

      private float bonusMultiplier_ ;
      /**
       * <code>float bonus_multiplier = 3;</code>
       */
      public float getBonusMultiplier() {
        return bonusMultiplier_;
      }
      /**
       * <code>float bonus_multiplier = 3;</code>
       */
      public Builder setBonusMultiplier(float value) {
        
        bonusMultiplier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float bonus_multiplier = 3;</code>
       */
      public Builder clearBonusMultiplier() {
        
        bonusMultiplier_ = 0F;
        onChanged();
        return this;
      }

      private float streakBonusMultiplier_ ;
      /**
       * <code>float streak_bonus_multiplier = 4;</code>
       */
      public float getStreakBonusMultiplier() {
        return streakBonusMultiplier_;
      }
      /**
       * <code>float streak_bonus_multiplier = 4;</code>
       */
      public Builder setStreakBonusMultiplier(float value) {
        
        streakBonusMultiplier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float streak_bonus_multiplier = 4;</code>
       */
      public Builder clearStreakBonusMultiplier() {
        
        streakBonusMultiplier_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings)
    }

    // @@protoc_insertion_point(class_scope:com.com.github.aeonlucid.pogoprotos.settings.master.quest.DailyQuestSettings)
    private static final com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings();
    }

    public static com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DailyQuestSettings>
        PARSER = new com.google.protobuf.AbstractParser<DailyQuestSettings>() {
      public DailyQuestSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DailyQuestSettings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DailyQuestSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DailyQuestSettings> getParserForType() {
      return PARSER;
    }

    public com.github.aeonlucid.pogoprotos.settings.master.Quest.DailyQuestSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;com/com.github/aeonlucid/pogoprotos/settin" +
      "gs/master/Quest.proto\0225com.com.github.aeonlu" +
      "cid.pogoprotos.settings.master.quest\"\177\n\022" +
      "DailyQuestSettings\022\027\n\017buckets_per_day\030\001 " +
      "\001(\005\022\025\n\rstreak_length\030\002 \001(\005\022\030\n\020bonus_mult" +
      "iplier\030\003 \001(\002\022\037\n\027streak_bonus_multiplier\030" +
      "\004 \001(\002B8\n/com.com.github.aeonlucid.pogoprotos" +
      ".settings.masterB\005Questb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_aeonlucid_pogoprotos_settings_master_quest_DailyQuestSettings_descriptor,
        new java.lang.String[] { "BucketsPerDay", "StreakLength", "BonusMultiplier", "StreakBonusMultiplier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
